// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK9BFsKSb5JjTkQh6pfMJxsO_kOOZ9Qgg',
    appId: '1:1038289397714:web:7b01d8ace5fce23757ca0b',
    messagingSenderId: '1038289397714',
    projectId: 'blightscan-2026',
    authDomain: 'blightscan-2026.firebaseapp.com',
    storageBucket: 'blightscan-2026.firebasestorage.app',
    measurementId: 'G-2TKYZD75EW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyeUXDsQoNLMLxIhkToWLyXSl0BbD1r7E',
    appId: '1:1038289397714:android:98ad313665b57ec557ca0b',
    messagingSenderId: '1038289397714',
    projectId: 'blightscan-2026',
    storageBucket: 'blightscan-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwWeCK9uRm0GzBs1Yj9Dk8xpAU87QIATU',
    appId: '1:1038289397714:ios:a9b3713390a3ad8457ca0b',
    messagingSenderId: '1038289397714',
    projectId: 'blightscan-2026',
    storageBucket: 'blightscan-2026.firebasestorage.app',
    iosBundleId: 'com.example.blightscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwWeCK9uRm0GzBs1Yj9Dk8xpAU87QIATU',
    appId: '1:1038289397714:ios:a9b3713390a3ad8457ca0b',
    messagingSenderId: '1038289397714',
    projectId: 'blightscan-2026',
    storageBucket: 'blightscan-2026.firebasestorage.app',
    iosBundleId: 'com.example.blightscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK9BFsKSb5JjTkQh6pfMJxsO_kOOZ9Qgg',
    appId: '1:1038289397714:web:b3b1f132a7134b4757ca0b',
    messagingSenderId: '1038289397714',
    projectId: 'blightscan-2026',
    authDomain: 'blightscan-2026.firebaseapp.com',
    storageBucket: 'blightscan-2026.firebasestorage.app',
    measurementId: 'G-B1HP2TP1LT',
  );
}
